1. NumPy vs list
    1. memory
        1. list: 56 + 8n + 28n
            1. empty list + element + pointer
        2. array: 112 + 4n
            1. empty array + element
        3. comparsion:
            1. int64: 4.5
            2. int32: 9
    2. speed

2. memory size of a unit in python
    1. getsizeof function from sys module

3. source of time in coumputer
    1. 1 jun 1970
    2. time.time() -> time in sec

4. calculate execution time
    1. time: 
        1. time.time(): current time in sec
    2. timeit:
        1. create timer object: Timer("func_name", "imprt func")
        2. calculate time: time_obj.timeit(10)

In [6]:
# derive a formule for memory usage of list and array

from sys import getsizeof as size
import numpy as np

# step1: empty
empty_list = []
empty_arr32 = np.array([])
empty_arr64 = np.array([], np.int64)
empty_list_size = size(empty_list)
empty_arr32_size = size(empty_arr32)
empty_arr64_size = size(empty_arr64)
print(empty_list_size, empty_arr32_size, empty_arr64_size)

# step2: extra size for each element
my_list = [1]
my_arr32 = np.array([1])
my_arr64 = np.array([1], np.int64)
my_list_size = size(my_list)
my_arr32_size = size(my_arr32)
my_arr64_size = size(my_arr64)
print(my_list_size, my_arr32_size, my_arr64_size)
print(size(my_list[0]))

# step3: make comparsion
n = 1000
arr_size = 112 + 8*n
list_size = 56 + 8*n + 28*n
print(list_size/arr_size)

56 112 112
64 116 120
28
4.444773175542406


In [9]:
# calculate execution time using 2 method

import time
from timeit import Timer
import numpy as np

##### method1: time module
vector_size = 1000000

li1 = list(range(vector_size))
li2 = list(range(vector_size))
# function for time of a sum operation on list
def time_li():
    t1 = time.time()
    li3 = [li1[i]+li2[i] for i in range(vector_size)]
    return time.time() - t1

arr1 = np.arange(vector_size)
arr2 = np.arange(vector_size)
# function for time of a sum operation on array
def time_arr():
    t1 = time.time()
    arr3 = arr1 + arr2
    return time.time() - t1

# now compare sum operation time
print("method1:\n","list:", time_li())
print("array:", time_arr())
print("list/arr:", time_li()/time_arr(),"\n\n")


##### method2: timeit module
# function for sum on list
def timer_li():
    li3 = [li1[i]+li2[i] for i in range(vector_size)]

# function for sum of array
def timer_arr():
    arr3 = arr1 + arr2

# creating timer object
timer_li_obj = Timer("timer_li","from __main__ import timer_li")
timer_arr_obj = Timer("timer_arr","from __main__ import timer_arr")

# comaprsion time of sum operasion
print("method2:\n","list:", timer_li_obj.timeit(10))
print("array:", timer_arr_obj.timeit(10))
print("list/arr:", timer_li_obj.timeit(10)/timer_arr_obj.timeit(10),"\n\n")

method1:
 list: 0.09701967239379883
array: 0.0020041465759277344
list/arr: 45.46749226006192 


method2:
 list: 1.400010660290718e-06
array: 7.00005330145359e-07
list/arr: 1.3333333333333333 




5. shape, dtype, order
    1. shape: tuple of array dimension
    2. dtype: create a data type object
    3. order: how data stored in memory
        1. column-major: 
            1. fortran-like
            2. order="F"
        2. row-major:
            1. c-like
            2. order="C"
        3. "A": F-order if input is F-order other wise C-order
        4. "K": F and C order preserved otherwise mosr similar order

6. subok:
    1. True: same dtype with input
    2. False
    3. where: in like versions 


7. matrix class
    1. np.mat()

8. like versions
    1. shape
    2. dtype

In [31]:
# special arrays in numpy
import numpy as np

# empty
empty_arr = np.empty((2,3), dtype=np.int64, order="C")
empty_arr

# empty_like #! subok
empty_like_arr = np.empty_like(np.mat(data="1 2;3 4"), subok=False,)
empty_like_arr

# eye #! N M k
eye_arr = np.eye(N=3, M=4, k=-1)
eye_arr

#  identity #! n, not suport order
identity_arr = np.identity(n=3)
identity_arr

# ones
ones_arr = np.ones((3,2), order="F")
ones_arr
# np.ones_like

# zeroes
zeroes_arr = np.zeros((4,2), order="F")
zeroes_arr

# full
full_arr = np.full((3,2), fill_value=3, order="F")
full_arr

# full_like #! dtype
full_like_arr = np.full_like(np.mat(data="1.2 2;3 4;1 3"), fill_value=3, subok=False)
full_like_arr


array([[3., 3.],
       [3., 3.],
       [3., 3.]])

9. creating array from existing data:
    1. np.array
        1. np.array
        2. np.asarray: copy=False
        3. np.asanyarray: copy=False, subok=True
    2. np.matrix: store data in 1d-memory(row-major)
    3. np.mat: store data in 2d-memory

10. is operator
    1. say 2 object are identical or not

11. find address of an object in memory
    1. id function: id(obj1)

12. find out that 2 object use same memory
    1. np.may_share_memory(obj1, obj2)

In [62]:
import numpy as np

# ! copy=False
arr1 = np.array([2, 3])
arr2 = np.array(arr1, copy=False)
arr2[0]= 1
print(arr1)
print(f"{id(arr1)}\n{id(arr2)}")
print(arr1 is arr2)
print(np.may_share_memory(arr1, arr2))

# ! subok=True
mat1 = np.matrix(data='1 2; 3 5')
arr3 = np.array(mat1, copy=False, subok=True)
print(f"{mat1 is arr3=}")


[1 3]
2358656569328
2358656569328
True
True
mat1 is arr3=True


13. cpu how access a data
    1. fetch
    2. decode
    3. execute

14. different parts of a instruction for cpu
    1. opcode
    2. address

15. cache?
    1. fast, expensive, small, memory

16. how reashape an array
    1. arr1.reshape(-1,3)
    2. arr1.shape

17. how see properties of an array
    1. arr1.flags

18. how ensure that array is stored in a contiguous memory location in row-major
    1. arr1 = np.ascontiguousarray(arr1)

19. how numpy transpose a matrix
    1. change its major
    2. arr1_trans = arr1.T

20. create a copy of a array in numpy
    1. shallow copy
        1. def: dont copy nested elements
        2. how: np.copy()
    2. deep copy
        1. def: copy all elements
        2. how: copy.deepcopy()

21. how create an array with different types
    1. arr1 = np.array([1, 'salam', [1, 2, 3]], dtype=object)

22. buffer
    1. def: is a queue
    2. usage: enable us to synchronize ourself with transsmitter or receiver
    3. in numpy: arr1 = np.frombuffer(buffer, dtype, count, offset)

In [14]:
import numpy as np
import copy

# reshape an array
# see properties of an array
arr4 = np.arange(6).reshape(-1, 3)
print(arr4.flags)

# make sure array is contiguous
arr4 = np.ascontiguousarray(arr4)
print(arr4.flags)

# transpose an array and see its properties #! numpy transpose
arr4_trans = arr4.T
print(arr4_trans.flags)

# shallow copy and #! dtype = object is mandatory
arr4 = np.array([1, 'pouria', [1, 3, 5]], dtype = object)
arr5 = np.copy(arr4)
arr5[2][0] = 10
print(arr4, arr5, arr4 is arr5)

# !deep copy 
arr5 = copy.deepcopy(arr4)
arr5[2][0] = 5
print(arr4, arr5, arr4 is arr5)

# !buffer in numpy
buffer = b"hello"
arr4 = np.frombuffer(buffer, dtype="S1", count=2, offset=3)
print(arr4)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

[1 'pouria' list([10, 3, 5])] [1 'pouria' list([10, 3, 5])] False
[1 'pouria' list([10, 3, 5])] [1 'pouria' list([5, 3, 5])] False
[b'l' b'o']


23. create an array from a
    1. function: arr1 = np.fromfunction(func, shape, dtype)
    2. iter: arr1 = np.fromiter(iter, dtype, count)
    3. string: arr1 = np.fromstring(string, dtype, count, sep)

24. load data from a text file
    1. arr1 = np.loadtext(file_name, dtype, skiprows, usecols)

25. define new data type in numpy
    1. dtype1 = np.dtype()
    2. input of dtype method: a list of tupes of data types

26. access data of a loaded text
    1. height_col = arr["height"]
    2. special data
        1. male = arr["sex"] == b"M"
        1. male_heights = arr["heights"][male]
    3. fmale = ~male

27. working with missing values
    1. provide converters for colomns that have missing values 
        1. converters: {3: func3, 4: func4}
        2. converter: assign toxic value instead of missing values
    2. load data: arr1 = np.loadtxt(converters)
    3. select aviable values: aviable_weight = arr1["weight"] > 0

    

In [26]:
import numpy as np

# create an array from a function
arr1 = np.fromfunction(lambda i,j: i==j, (3,3), dtype=int)
print(arr1)

# from a iter
it = (i**2 for i in range(6))
arr1 = np.fromiter(it, dtype=int, count=3)
print(arr1)

# from string
name = '1 2 3 45'
arr1 = np.fromstring(name, dtype=int, sep=' ')
print(arr1)

# !load text, and np.dtype
file_name = "file1.txt"
dtype1 = np.dtype([("sex", "S2"), ("height", "f2")])
arr2 = np.loadtxt(file_name, dtype=dtype1, skiprows=9, usecols=(1, 3))
print(arr2)

# access data from a loaded text file #! important
male = arr2["height"] == b"M"

# extract special data of a loaded text #! important
avg_male_height = arr2["height"][male].mean()
avg_fmale_height = arr2["height"][~male].mean()

# working with weight colomn that has missing values #! missing values in numpy
def correct_missing_weights(weight):
    try:
        return float(weight)
    except ValueError:
        return float(-100)

dtype2 = np.dtype([("sex", "S2"), ("weight", "f2")])
arr3 = np.loadtxt(file_name, dtype=dtype2, skiprows=9, usecols=(1, 4), converters={4:correct_missing_weights})
aviable_weights = arr3["weight"] > 0
avg_male_weight = arr3["weight"][aviable_weights & male].mean()
avg_fmale_weight = arr3["weight"][aviable_weights & ~male].mean()



[[ True False False]
 [False  True False]
 [False False  True]]
[0 1 4]
[ 1  2  3 45]


28. I/O NPY and NPZ
    1. npy
        1. def: enable us store single array
        2. save: np.save("file_name.npy", arr1, allow_pickle=True, fix_imports=True)
            1. pickle
            2. fix_imports: fix difference between python 2 and 3 import files
        3. load: loaded_arr = np.load("file_name.npy", allow_pickle=False, fix_imports=True, encoding="ASCII")
            1. why allow_pickle is False: security(from numpy 1.16.3 and later)
    2. npz
        1. def: can store multiple array
        2. save: np.savez("file_name.npz", *args **kwargs)
            1. kwargs: np.savez("file_name.npz", arr1 = arr1, arr2 = arr2)
            2. compressed: np.savez_compressed("file_name.npz")
        2. load
            1. loaded_file = np.load("file_name.npz")
            2. see keywords: loaded_file.files
            3. access wanted array: loaded_file["arr1"]

29. list comprehension with multiple variable
    1. [i+j for i in range(2) for j in range(3)]

30. I/O txt files
    1. load: np.loadtxt()
        1. attributes: file_name, dtype, skiprows, usecols, converters
    2. load with regex format: np.fromregex()
        1. attributes: file_name, regexp, dtype
    3. save: np.savetxt()
        1. attributes: fname, X, fmt="%.18e", header="", footer="", comment="#", newline="n", encoding=None
        2. limit: only 1d and 2d array

31. convert numpy array to python list
    1. shallow convert: list1 = list(arr1)
    2. deep convert: list1 = arr1.tolist()
    3. shallow vs deep:
        1. shallow convert: doesnot convert insider element to python built-in type
        2. deep convert:
        
32. assign a object to an anonymos variable: _ = object1

In [46]:
import numpy as np

# create array #!mulltiple list comprehension
arr1 = np.array([i+j for i in range(2) for j in range(3)])

#npy format
np.save("fileNpy.npy", arr1, allow_pickle=True, fix_imports=True)
loaded_npy = np.load("fileNpy.npy") 
print("load .npy:", loaded_npy)

# npz format
np.savez_compressed("fileNpz.npz", arr1 = arr1)
loaded_npz = np.load("fileNpz.npz")
print("load .npz:",loaded_npz)
print("access to .npz files:", loaded_npz.files)
print("print arr1 from .npz:", loaded_npz["arr1"])

#loading using  np.fromregex
# step1: create a txt file
file1 = open("fileTxt.txt", "w")
_ = file1.write("123 Pouria\n32 Nastaran\n1987 Sarmasti") #! anonymos variable
file1.close()
# step2: np.fromregex
regex = r"(\d+)\s+(.+)" #! dtype must match to this ()
loaded_reg = np.fromregex("fileTxt.txt", regexp=regex, dtype=[("num", "f2"),("name", "S10")])
print(loaded_reg)

# save an array to a .txt file
arr2 = np.arange(20).reshape(-1,4)
np.savetxt(fname="arrTxt.txt",X=arr2, fmt="%5.2f")







load .npy: [0 1 2 1 2 3]
load .npz: <numpy.lib.npyio.NpzFile object at 0x00000213F268CA50>
access to .npz files: ['arr1']
print arr1 from .npz: [0 1 2 1 2 3]
[( 123., b'Pouria') (  32., b'Nastaran') (1987., b'Sarmasti')]


33. create copy of a slice of an array
    1. arr2 = arr1[2:5].copy()
    2. views: by array-slicing we create views not copy

34. access an 2d-array elements
    1. arr1[2][3]
    2. arr1[2, 3]

35. 3d-array: k, j, i
    1. access an element: arr3d[arrTh, rowTh, colTh]


In [8]:
import numpy as np

# access array elements
arr2d = np.arange(16).reshape(4,4)
print(arr2d)
print(arr2d[1,2], arr2d[1][2])

# 3d arrat #! recursive: array, row, col
arr3d = np.arange(27).reshape(3, 3, 3)
print(arr3d)
# access 2th array
print(arr3d[1])
# access an element in 2th array
print(arr3d[1, 2, 0])
print(arr3d[1:, :2, 2:])





[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
6 6
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
15
[[[11]
  [14]]

 [[20]
  [23]]]


36. boolean indexing
    1. def: use a boolean array to access data of another array
    2. syntax:
        1. arr1[row_bool_arr, col_bool_arr]
    3. important
        1. boolean indexing return a copy
        2. operator between boolean_array: &, |, ~
        3. boolean indexing never fails!!!!!

37. access specific data in an array
    1. specific rows: arr1[[2, 3, 4]]
    2. specific cols: arr1[:, [2, 3, 4]]
    3. specific elements: arr1[[2, 3, 4], [2, 3, 4]]
    4. specific rows and cols: arr1[[2, 3, 4]][:,[2, 3, 4]]
    5. this indexing create a copy not view

In [37]:
import numpy as np

# create data and name #! np.random.randint
names = np.array(['pouria', 'nastaran', 'parisa', 'payam', 'ali', 'mohtaram', 'ali'])
data = np.random.randint(0, 10, size=(7,4))

# create boolean index for rows
row_bool = names == 'pouria'
# boolean indexing #! return copy
pouria = data[row_bool, :3]
pouria[0,0] = 125
print(data, pouria)
print(data[~row_bool])

# specific data in an array
arr1 = np.arange(25).reshape(5, 5)
print("\n\n\n", arr1)
# rows
print("rows:\n",arr1[[0, 2]])
# cols
print("cols:\n",arr1[:,[0, 2]])
# elements
print("elements:\n", arr1[[0, 2], [0, 2]])
# rows and cols
print("rows and cols:\n", arr1[[0, 2]][:, [0, 2]])

# copy test #! fancy indexing also create copy
arr2 = arr1[[1]][:,[2]]
print(arr2.shape)
arr2[0, 0] = -10
print(arr1, arr2)

[[1 3 8 4]
 [2 9 6 9]
 [6 8 5 7]
 [2 0 1 1]
 [2 9 5 4]
 [4 5 3 3]
 [6 8 7 2]] [[125   3   8]]
[[2 9 6 9]
 [6 8 5 7]
 [2 0 1 1]
 [2 9 5 4]
 [4 5 3 3]
 [6 8 7 2]]



 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
rows:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]]
cols:
 [[ 0  2]
 [ 5  7]
 [10 12]
 [15 17]
 [20 22]]
elements:
 [ 0 12]
rows and cols:
 [[ 0  2]
 [10 12]]
(1, 1)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] [[-10]]


38. 